### ISSUE TITLE
Remove "current" links

### ISSUE THREAD

**Issue by Krinkle** [tool-labs/static#10]
Now that this project is still fresh, please remove this. These are not good for anything. Projects that use any of these libraries obviously aren't magically compatible with every future version. They should be responsible for upgrading when and if they want to.

Having `current` only encourages bad programming practices and eventually only causes trouble for everybody involved (us, other tool labs developers, end users).

**Comment by robinkrahl** [comment]
OK for me.  If you want to perform this change, feel free to do it.  Otherwise I’ll eventually deal with it.
