### ISSUE TITLE
Tweak .lighttpd.conf

### ISSUE THREAD

**Issue by Hedonil** [tool-labs/static#12]
Static's purpose is to serve static, cached content with high throughput. In this respect some tweaks to .lighttpd.conf, to increase its power. 
https://tools.wmflabs.org/paste/view/73037663

Provided a test-setup for checks with the above mentioned .lighttpd.conf settings
http://tools.wmflabs.org/newwebtest/res/

**Comment by robinkrahl** [comment]
@Hedonil Is this still up-to-date?  (Sorry for the delay.)

**Comment by Krinkle** [comment]
Is this still relevant now that we're using http://tools-static.wmflabs.org/?

It seems that server already takes care of proper client-side caching (by using ETag instead of max-age).

**Comment by ricordisamoa** [comment]
> Is this still relevant now that we're using http://tools-static.wmflabs.org/?

No, I think it can be closed.
