### ISSUE TITLE
host free (libre) fonts

### ISSUE THREAD

**Issue by ricordisamoa** [tool-labs/static#14]
[Glyphicons](http://glyphicons.com) Halflings is stored as part of the Twitter Boostrap.
What about hosting some other icon fonts, such as [Font Awesome](//fortawesome.github.io/Font-Awesome/) and [Elusive](//github.com/aristath/elusive-iconfont), or even some of [Google web fonts](//www.google.com/fonts)?

**Comment by robinkrahl** [comment]
No objections.  I added Font Awesome as an example with 8eecf34f33f0e6f1d77726a972acd818112cc535.  To add other fonts, please open a pull request (preferred :)) or name the fonts you need.

**Comment by ricordisamoa** [comment]
#18 :disappointed:
