### ISSUE TITLE
provide anonymous access statistics

### ISSUE THREAD

**Issue by ricordisamoa** [tool-labs/static#15]
It would be useful to know how many tools are using a resource.

**Comment by robinkrahl** [comment]
Good idea, thanks.  As an example I created a script that generates [this list](https://tools.wmflabs.org/static/access-log.txt) from the latest 100,000 entries in the `access.log`.  I’ll create a CSV output of that script and then display the tools using a resource via JavaScript.

**Comment by robinkrahl** [comment]
@ricordisamoa The new dynamic detail view now shows the tools that used this package within the last 30 days, e. g. [for jQuery 2.1.0](https://tools.wmflabs.org/static-browser/show/jquery/2.1.0)
