### ISSUE TITLE
Dynamically generate the overview page

### ISSUE THREAD

**Issue by robinkrahl** [tool-labs/static#16]
The index page should be generated automatically from description files added to the resources.  These files must contain 
- the name of the resource,
- the version of the resource,
- the license of the resource,
- the main files.

Additional features could be a search for resources or files.

**Comment by Krinkle** [comment]
Bold proposal:
- Add `index.json` inside each `res/:project` directory with the relevant information.
- Convert `index.html` to `index.php` and use glob to fetch `index.json` files, sort, and render HTML in a loop.
- (maybe) Provide API mode that aggregates all `index.json` files into a larger index.

**Comment by robinkrahl** [comment]
@Krinkle +1, just some details:
- I’d put the `index.json` in `res/:project/:version`, possibly with a fallback in `res/:project/:version`, as there might changes to licenses or file names in different versions.
- I’d create a tool `static-browser` so that the browsing does not affect serving the static files.  Furthermore, out of personal preferences I’d use Python and Flask.
- I’d integrate the usage data as proposed in #15.

Additionally, there should be a Travis script checking all JSON files in `static`.

Are you okay with putting your contributions to index.html, portal.js and portal.css under the MIT license when I’m moving to the dynamic index?

**Comment by robinkrahl** [comment]
Have a look at [static-browser](https://github.com/tool-labs/static-browser) available on [Tool Labs](https://tools.wmflabs.org/static-browser/).

**Comment by Krinkle** [comment]
@ireas Yes, I hereby release my contributions to the [tool-labs/static](https://github.com/tool-labs/static) project on GitHub under the MIT license.

**Comment by robinkrahl** [comment]
@Krinkle Thanks.

<hr />

I just created a redirect from `/static/` and `/static/index.html` to `/static-browser/`, so I’m closing this issue.
