### ISSUE TITLE
Show the logos on static-browser

### ISSUE THREAD

**Issue by sitic** [tool-labs/static#17]
The new [static-browser](https://tools.wmflabs.org/static-browser/) looks very nice, thanks for that.

But I'm missing the [list of logos](http://tools.wmflabs.org/static/res/logos/), which the old setup showed. Could that be added again?

Thanks

**Comment by robinkrahl** [comment]
Yes, I’ll add the logos, but at the moment I’m not quite sure how / in which structure.

**Comment by robinkrahl** [comment]
Tracked in tool-labs/static-browser#3.
