### ISSUE TITLE
CORS policy prevents fonts from being loaded

### ISSUE THREAD

**Issue by ricordisamoa** [tool-labs/static#18]
[bootstrap.min.css](//tools-static.wmflabs.org/static/bootstrap/3.2.0/css/bootstrap.min.css) is quite useless for projects relying on Glyphicons, since loading fonts via `static` appears to be forbidden:
`Font from origin 'http://tools-static.wmflabs.org' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://tools.wmflabs.org' is therefore not allowed access.`

**Comment by Krinkle** [comment]
CORS should not apply to the display of fonts, only the reading of loaded data. Perhaps another script on the page is doing something to cause this. Can you link to an example page?

**Comment by ricordisamoa** [comment]
http://tools.wmflabs.org/ricordisamoa/cors.html

**Comment by ricordisamoa** [comment]
Any updates?
My projects could use some more webfonts but I don't want to rely on third-party services.

**Comment by Krinkle** [comment]
Interesting. I wasn't aware of the Same-origin policy applying to fonts.

While it definitely doesn't hurt, I previously thought it shouldn't be needed. However considering fonts need this, let's add this.

Another reason is to allow inspection of styles by libraries such as Autoprefixer.

**Comment by ricordisamoa** [comment]
https://phabricator.wikimedia.org/T93466
